
SELECT current timestamp FROM sysibm.sysdummy1;
LOAD FROM "/tmp/subregion_markup.exp" OF DEL MODIFIED BY COLDEL, METHOD P (1, 2, 3, 4, 5) MESSAGES "/tmp/subregion_markup_load.msg" REPLACE INTO VALIDATION.SUBREGION_MARKUP (PAIS_UID, TILENAME, SUBREGIONNAME, SUBREGIONTILENAME, MARKUP_ID) STATISTICS USE PROFILE COPY NO INDEXING MODE DEFERRED LOCK WITH FORCE;
SELECT current timestamp FROM sysibm.sysdummy1;

