DROP TABLE PAIS.STAGINGDOC;
DROP TABLE PAIS.LOADING_LOG;
DROP TABLE PAIS.METADOC;
DROP TABLE PAIS.PAIS;
DROP TABLE PAIS.PROJECT;
DROP TABLE PAIS.GROUP;
DROP TABLE PAIS.USER;
DROP TABLE PAIS.COLLECTION;
DROP TABLE PAIS.WHOLESLIDEIMAGEREFERENCE;
DROP TABLE PAIS.REGION;
DROP TABLE PAIS.SPECIMEN;
DROP TABLE PAIS.ANATOMICENTITY;
DROP TABLE PAIS.PATIENT;

DROP TABLE PAIS.OBSERVATION_QUANTIFICATION_ORDINAL;
DROP TABLE PAIS.OBSERVATION_QUANTIFICATION_NOMINAL;
DROP TABLE PAIS.ANNOTATION_MARKUP;
DROP TABLE PAIS.MARKUP_POLYGON;
DROP TABLE PAIS.MARKUP_POLYGON_HUMAN;

DROP TABLE PAIS.MARKUP_POLYGON_NUCLEUS_HUMAN;
DROP TABLE PAIS.MARKUP_POLYGON_NUCLEUS;

DROP TABLE PAIS.PROVENANCE;
DROP TABLE PAIS.ALGORITHM;
DROP TABLE PAIS.PARAMETER;
DROP TABLE PAIS.INPUTFILEREFERENCE;

DROP TABLE PAIS.CALCULATION_FLAT;
DROP TABLE PAIS.CALCULATION_DICTIONARY;
DROP TABLE PAIS.OBSERVATION_DICTIONARY;


CREATE TABLE PAIS.STAGINGDOC(
	UID	 		VARCHAR(64),  
	TILENAME 		VARCHAR(64), 
	BLOB 			BLOB (1024M) NOT  LOGGED  NOT  COMPACT, 
	STATUS 			VARCHAR(24) WITH DEFAULT 'INCOMPLETE',
	INSERT_TIME		TIMESTAMP,
	COMPLETE_TIME		TIMESTAMP,
	COMPLETE_COUNT		INTEGER,
	LOADING_TIME		DECIMAL(6,2),
	FILE_NAME		VARCHAR(256),
	SEQUENCE_NUMBER		INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE), 
        PRIMARY KEY(SEQUENCE_NUMBER)
	) in LOBTBS;

CREATE TABLE PAIS.LOADING_LOG(
    SEQUENCE_NUMBER             INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1, NO CACHE),
    FAUILURE_TIME 	        TIMESTAMP,
    FILE_NAME	                VARCHAR(256),
    FAILURE_MESSAGE	        VARCHAR(3000) 
);

--Added:
  CREATE TABLE PAIS.METADOC(
    UID                         VARCHAR(640) NOT NULL,
    XMLDOC                      XML,
    INSERTTIME                  TIMESTAMP
  );


  CREATE TABLE PAIS.PAIS(
    PAIS_ID			DECIMAL(30,0) NOT NULL,
    PAIS_UID			VARCHAR(64)   NOT NULL,
    NAME			VARCHAR(64),
    DATETIME			VARCHAR(64),
    PAISVERSION			VARCHAR(64),
    CODEVALUE			VARCHAR(64),  
    CODEMEANING			VARCHAR(64),
    CODINGSCHEMEDESIGNATOR	VARCHAR(64),
    CODINGSCHEMEVERSION		VARCHAR(64),  
    COMMENT			VARCHAR(128)
  );



CREATE TABLE PAIS.PROJECT(  
  PROJECT_ID 			DECIMAL(30,0) NOT NULL,
  PROJECT_UID			VARCHAR(64),
  NAME	 			VARCHAR(64),
  URI				VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  


CREATE TABLE PAIS.GROUP(  
  GROUP_ID 			DECIMAL(30,0) NOT NULL,
  GROUP_UID			VARCHAR(64),
  NAME	 			VARCHAR(64),
  URI				VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  


CREATE TABLE PAIS.USER(
  USER_ID			DECIMAL(30,0) NOT NULL,
  LOGINNAME			VARCHAR(64),
  NAME				VARCHAR(64),
  NUMBERWITHINROLEOFCLINICALTRIAL INTEGER,
  ROLEINTRIAL			VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL
);  



CREATE TABLE PAIS.COLLECTION(  
  COLLECTION_ID 		DECIMAL(30,0) NOT NULL,
  COLLECTION_UID		VARCHAR(64) NOT NULL,
  NAME	 			VARCHAR(64),
  ROLE				VARCHAR(64),
  METHODNAME			VARCHAR(64) NOT NULL,
  SEQUENCENUMBER		INTEGER NOT NULL,
  STUDYDATETIME	        	VARCHAR(64),
  PAIS_UID			VARCHAR(64) NOT NULL 
);  
  
 
 

 CREATE TABLE PAIS.WHOLESLIDEIMAGEREFERENCE(
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,
  IMAGEREFERENCE_UID		VARCHAR(64),
  FILEREFERENCE			VARCHAR(64),
  URI				VARCHAR(64),
  RESOLUTION			DOUBLE,
  ZAXISRESOLUTION		DOUBLE,
  ZAXISCOORDINTE		DOUBLE,
  PAIS_UID			VARCHAR(64)   NOT NULL 
);    
  


 CREATE TABLE PAIS.REGION(
  REGION_ID			DECIMAL(30,0) NOT NULL,
  NAME				VARCHAR(64) NOT NULL,
  X				DOUBLE,
  Y				DOUBLE,
  HEIGHT			DOUBLE,
  WIDTH				DOUBLE,
  ZOOMRESOLUTION		DOUBLE,
  COORDINATERESOLUTION		DOUBLE,
  COORDINATEREFERENCE		VARCHAR(64),
  POLYGON  			DB2GSE.ST_POLYGON INLINE LENGTH 512,  
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,
  PAIS_UID			VARCHAR(64)   NOT NULL
) in spatialtbs32k;   
  

 CREATE TABLE PAIS.SPECIMEN(
  SPECIMEN_ID			DECIMAL(30,0) NOT NULL,
  SPECIMEN_UID			VARCHAR(64),
  TYPE				VARCHAR(64),
  STAIN				VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,    
  PAIS_UID			VARCHAR(64)   NOT NULL 
);    



 CREATE TABLE PAIS.ANATOMICENTITY(
  ANATOMICENTITY_ID		DECIMAL(30,0) NOT NULL,
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,    
  PAIS_UID			VARCHAR(64)   NOT NULL
);   
 


CREATE TABLE PAIS.PATIENT(
  PATIENT_ID 			DECIMAL(30,0) NOT NULL,
  PATIENTID 			VARCHAR(64),  
  SEX				VARCHAR(64),  
  BIRTHDATE			VARCHAR(64),  
  ETHNICGROUP			VARCHAR(64),
  IMAGEREFERENCE_ID		DECIMAL(30,0) NOT NULL,  
  PAIS_UID			VARCHAR(64)   NOT NULL     
);


-- Removed: CALCULATION_FLAT
-- Added:
 CREATE TABLE PAIS.CALCULATION_DICTIONARY(
  DICTIONARY_ID			DECIMAL(30,0) NOT NULL, 
  METHODNAME			VARCHAR(64),
  CALCULATION_NAME		VARCHAR(64),  
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  DESCRIPTION			VARCHAR(512),
  DATATYPE			VARCHAR(64),
  UNITOFMEASURE			VARCHAR(64)
);

-- Added:
 CREATE TABLE PAIS.OBSERVATION_DICTIONARY(
  DICTIONARY_ID			DECIMAL(30,0) NOT NULL, 
  METHODNAME			VARCHAR(64),
  OBSERVATION_NAME		VARCHAR(64),  
  CODEVALUE			VARCHAR(64),  
  CODEMEANING			VARCHAR(64),
  CODINGSCHEMEDESIGNATOR	VARCHAR(64),
  CODINGSCHEMEVERSION		VARCHAR(64),
  DESCRIPTION			VARCHAR(512),
  DATATYPE			VARCHAR(64),
  UNITOFMEASURE			VARCHAR(64)
);


  
   CREATE TABLE PAIS.OBSERVATION_QUANTIFICATION_ORDINAL(
    OBSERVATION_ID 		DECIMAL(30,0) NOT NULL,
    OBSERVATION_NAME		VARCHAR(64),
    ANNOTATORCONFIDENCE		DOUBLE,
    
    QUANTIFICATION_ID		DECIMAL(30,0) NOT NULL,
    QUANTIFICATION_NAME		VARCHAR(64),
    QUANTIFICATION_VALUE	DOUBLE,
    QUANTIFICATION_DATATYPE	VARCHAR(64),
    PROVENANCE_ID		DECIMAL(30,0),
    MARKUP_ID			DECIMAL(30,0),

    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,   
    TILENAME			VARCHAR(64) NOT NULL,    
    PAIS_UID			VARCHAR(64)   NOT NULL,    
    OBSERVATION_DICTIONARY_ID   DECIMAL(30,0)
 ) 
COMPRESS YES
IN SPATIALTBS32K;


   CREATE TABLE PAIS.OBSERVATION_QUANTIFICATION_NOMINAL(
    OBSERVATION_ID 		DECIMAL(30,0) NOT NULL,
    OBSERVATION_NAME		VARCHAR(64),
    ANNOTATORCONFIDENCE		DOUBLE,
    
    QUANTIFICATION_ID		DECIMAL(30,0) NOT NULL,
    QUANTIFICATION_NAME		VARCHAR(64),
    QUANTIFICATION_VALUE	VARCHAR(64),
    PROVENANCE_ID		DECIMAL(30,0),
    MARKUP_ID			DECIMAL(30,0),

    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,   
    TILENAME			VARCHAR(64) NOT NULL,    
    PAIS_UID			VARCHAR(64)   NOT NULL,    
    OBSERVATION_DICTIONARY_ID   DECIMAL(30,0)
 ) 
COMPRESS YES
IN SPATIALTBS32K;
 
 
CREATE TABLE PAIS.ANNOTATION_MARKUP(
    ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
    MARKUP_ID			DECIMAL(30,0) NOT NULL,
    PAIS_UID			VARCHAR(64)   NOT NULL
 ) IN SPATIALTBS32K;

 


CREATE TABLE PAIS.MARKUP_POLYGON  (
   MARKUP_ID			DECIMAL(30,0) NOT NULL,      
   NAME				VARCHAR(64),
   GEOMETRICSHAPE_ID		DECIMAL(30,0) NOT NULL,  
   ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
   POLYGON  			DB2GSE.ST_POLYGON INLINE LENGTH 30000,
   PROVENANCE_ID		DECIMAL(30,0),   
   TILENAME			VARCHAR(64) NOT NULL,
   PAIS_UID 			VARCHAR(64) NOT NULL,
   CENTROID_X			DOUBLE,
   CENTROID_Y			DOUBLE
) 
COMPRESS YES
IN spatialtbs32k   
DISTRIBUTE BY HASH (TILENAME)
;


CREATE TABLE PAIS.MARKUP_POLYGON_HUMAN  (
   MARKUP_ID			DECIMAL(30,0) NOT NULL,      
   NAME				VARCHAR(64),
   GEOMETRICSHAPE_ID		DECIMAL(30,0) NOT NULL,  
   ANNOTATION_ID		DECIMAL(30,0) NOT NULL,  
   POLYGON  			DB2GSE.ST_POLYGON,
   PROVENANCE_ID		DECIMAL(30,0),   
   TILENAME			VARCHAR(64)   NOT NULL,
   PAIS_UID 			VARCHAR(64) NOT NULL
) 
COMPRESS YES
IN spatialtbs32k;   


CREATE TABLE PAIS.MARKUP_POLYGON_NUCLEUS_HUMAN  (
   MARKUP_ID                    DECIMAL(30,0) NOT NULL,
   NAME                         VARCHAR(64),
   GEOMETRICSHAPE_ID            DECIMAL(30,0) NOT NULL,
   ANNOTATION_ID                DECIMAL(30,0) NOT NULL,
   POLYGON                      DB2GSE.ST_POLYGON,
   PROVENANCE_ID                DECIMAL(30,0),
   TILENAME                     VARCHAR(64)   NOT NULL,
   PAIS_UID                     VARCHAR(64) NOT NULL
)
COMPRESS YES
IN spatialtbs32k;

CREATE TABLE PAIS.MARKUP_POLYGON_NUCLEUS  (
   MARKUP_ID                    DECIMAL(30,0) NOT NULL,
   NAME                         VARCHAR(64),
   GEOMETRICSHAPE_ID            DECIMAL(30,0) NOT NULL,
   ANNOTATION_ID                DECIMAL(30,0) NOT NULL,
   POLYGON                      DB2GSE.ST_POLYGON,
   PROVENANCE_ID                DECIMAL(30,0),
   TILENAME                     VARCHAR(64)   NOT NULL,
   PAIS_UID                     VARCHAR(64) NOT NULL
)
COMPRESS YES
IN spatialtbs32k;



CREATE TABLE PAIS.PROVENANCE(
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,    
  SCOPE				VARCHAR(64),    
  PAIS_UID 			VARCHAR(64) NOT NULL   
);


CREATE TABLE PAIS.ALGORITHM(
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL,    
  NAME				VARCHAR(64),
  VERSION			VARCHAR(64),
  URI				VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,  
  PAIS_UID 			VARCHAR(64)   NOT NULL 
);  

CREATE TABLE PAIS.PARAMETER(
  PARAMETER_ID			DECIMAL(30,0) NOT NULL,    
  NAME				VARCHAR(64),
  VALUE				VARCHAR(64),
  DATATYPE			VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL,    
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL, 
  PAIS_UID 			VARCHAR(64)   NOT NULL   
);  
  

CREATE TABLE PAIS.INPUTFILEREFERENCE(
  INPUTFILEREFERENCE_ID 	DECIMAL(30,0) NOT NULL,    
  FILEREFERENCE			VARCHAR(64),
  URI				VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0) NOT NULL, 
  ALGORITHM_ID			DECIMAL(30,0) NOT NULL,      
  PAIS_UID 			VARCHAR(64)   NOT NULL    
);


 CREATE TABLE PAIS.CALCULATION_FLAT(
  ANNOTATION_ID			DECIMAL(30,0) NOT NULL,  
  ANNOTATION_NAME		VARCHAR(64),
  PROVENANCE_ID			DECIMAL(30,0),
  MARKUP_ID			DECIMAL(30,0) NOT NULL, 
  TILENAME			VARCHAR(64)   NOT NULL,
  PAIS_UID			VARCHAR(64)   NOT NULL,  
  CALCULATION_DICTIONARY_ID	DECIMAL(30,0), 

  AREA 				DOUBLE,
  PERIMETER 			DOUBLE,
  ECCENTRICITY 			DOUBLE,
  CIRCULARITY	 		DOUBLE,
  MAJOR_AXIS 			DOUBLE,
  MINOR_AXIS 			DOUBLE,  
  EXTENT_RATIO 			DOUBLE,
  MEAN_INTENSITY 		DOUBLE,
  MAX_INTENSITY  		DOUBLE,
  MIN_INTENSITY  		DOUBLE,
  STD_INTENSITY  		DOUBLE,
  ENTROPY 			DOUBLE,
  ENERGY 			DOUBLE,
  SKEWNESS 			DOUBLE,
  KURTOSIS 			DOUBLE,
  MEAN_GRADIENT_MAGNITUDE 	DOUBLE,
  STD_GRADIENT_MAGNITUDE 	DOUBLE,   
  ENTROPY_GRADIENT_MAGNITUDE 	DOUBLE,   
  ENERGY_GRADIENT_MAGNITUDE 	DOUBLE,   
  SKEWNESS_GRADIENT_MAGNITUDE 	DOUBLE, 
  KURTOSIS_GRADIENT_MAGNITUDE 	DOUBLE,   
  SUM_CANNY_PIXEL 		DOUBLE,
  MEAN_CANNY_PIXEL 		DOUBLE,
CYTO_H_MeanIntensity 		DOUBLE, 
CYTO_H_MeanMedianDifferenceIntensity DOUBLE, 
CYTO_H_MaxIntensity 		DOUBLE, 
CYTO_H_MinIntensity 		DOUBLE, 
CYTO_H_StdIntensity 		DOUBLE,
CYTO_H_Entropy 			DOUBLE, 
CYTO_H_Energy 			DOUBLE, 
CYTO_H_Skewness 		DOUBLE, 
CYTO_H_Kurtosis 		DOUBLE,
CYTO_H_MeanGradMag 		DOUBLE, 
CYTO_H_StdGradMag 		DOUBLE, 
CYTO_H_EntropyGradMag 		DOUBLE, 
CYTO_H_EnergyGradMag 		DOUBLE,
CYTO_H_SkewnessGradMag 		DOUBLE, 
CYTO_H_KurtosisGradMag 		DOUBLE, 
CYTO_H_SumCanny 		DOUBLE, 
CYTO_H_MeanCanny 		DOUBLE,
CYTO_E_MeanIntensity 		DOUBLE, 
CYTO_E_MeanMedianDifferenceIntensity DOUBLE, 
CYTO_E_MaxIntensity 		DOUBLE, 
CYTO_E_MinIntensity 		DOUBLE, 
CYTO_E_StdIntensity 		DOUBLE,
CYTO_E_Entropy 			DOUBLE, 
CYTO_E_Energy 			DOUBLE, 
CYTO_E_Skewness 		DOUBLE, 
CYTO_E_Kurtosis 		DOUBLE,
CYTO_E_MeanGradMag 		DOUBLE, 
CYTO_E_StdGradMag 		DOUBLE, 
CYTO_E_EntropyGradMag 		DOUBLE, 
CYTO_E_EnergyGradMag 		DOUBLE,
CYTO_E_SkewnessGradMag 		DOUBLE, 
CYTO_E_KurtosisGradMag		 DOUBLE, 
CYTO_E_SumCanny 		DOUBLE, 
CYTO_E_MeanCanny 		DOUBLE,
CYTO_G_MeanIntensity		DOUBLE, 
CYTO_G_MeanMedianDifferenceIntensity DOUBLE, 
CYTO_G_MaxIntensity 		DOUBLE, 
CYTO_G_MinIntensity 		DOUBLE, 
CYTO_G_StdIntensity 		DOUBLE,
CYTO_G_Entropy 			DOUBLE, 
CYTO_G_Energy 			DOUBLE, 
CYTO_G_Skewness 		DOUBLE, 
CYTO_G_Kurtosis 		DOUBLE,
CYTO_G_MeanGradMag 		DOUBLE, 
CYTO_G_StdGradMag 		DOUBLE, 
CYTO_G_EntropyGradMag 		DOUBLE, 
CYTO_G_EnergyGradMag 		DOUBLE,
CYTO_G_SkewnessGradMag 		DOUBLE, 
CYTO_G_KurtosisGradMag 		DOUBLE, 
CYTO_G_SumCanny 		DOUBLE, 
CYTO_G_MeanCanny		DOUBLE   
 ) 
COMPRESS YES
IN SPATIALTBS32K
DISTRIBUTE BY HASH (TILENAME)
;

