--Example patient 0001:
--TCGA-02-0001-01Z-00-DX1_20x_20x_NS-MORPH_1, 203172
--TCGA-02-0001-01Z-00-DX2_20x_20x_NS-MORPH_1, 511628  
--TCGA-02-0001-01Z-00-DX3_20x_20x_NS-MORPH_1, 574582

-- Default: pais_uid='CGA-02-0001-01Z-00-DX2_20x_20x_NS-MORPH_1' patientid ='001'

-----------------------------------------------------------------------
echo 'meanfeaturevectorcovsingleslide';
insert into bchmk.querytime SELECT 'meanfeaturevectorcovsingleslide', current timestamp, null  FROM sysibm.sysdummy1;

SELECT  
       AVG(AREA),AVG(PERIMETER),AVG(ECCENTRICITY),AVG(CIRCULARITY),AVG(MAJOR_AXIS),AVG(MINOR_AXIS), 
       AVG(EXTENT_RATIO), AVG(MEAN_INTENSITY), AVG(MAX_INTENSITY),AVG(MIN_INTENSITY),AVG(STD_INTENSITY),
       AVG(ENTROPY),AVG(ENERGY),AVG(SKEWNESS),AVG(KURTOSIS),AVG(MEAN_GRADIENT_MAGNITUDE),
       AVG(STD_GRADIENT_MAGNITUDE),AVG(ENTROPY_GRADIENT_MAGNITUDE),AVG(ENERGY_GRADIENT_MAGNITUDE),
       AVG(SKEWNESS_GRADIENT_MAGNITUDE),AVG(KURTOSIS_GRADIENT_MAGNITUDE),AVG(SUM_CANNY_PIXEL),
       AVG(MEAN_CANNY_PIXEL),
      COVARIANCE(AREA, PERIMETER) AS COV_AREA_PERIMETER,
      COVARIANCE(AREA, ECCENTRICITY) AS COV_AREA_ECCENTRICITY,
      COVARIANCE(AREA, CIRCULARITY) AS COV_AREA_CIRCULARITY,           
      COVARIANCE(AREA, MAJOR_AXIS) AS COV_AREA_MAJOR_AXIS,
      COVARIANCE(AREA, MINOR_AXIS) AS COV_AREA_MINOR_AXIS,
      COVARIANCE(AREA, EXTENT_RATIO) AS COV_AREA_EXTENT_RATIO,
      COVARIANCE(AREA, MEAN_INTENSITY) AS COV_AREA_MEAN_INTENSITY,
      COVARIANCE(AREA, MAX_INTENSITY) AS COV_AREA_MAX_INTENSITY,
      COVARIANCE(AREA, MIN_INTENSITY) AS COV_AREA_MIN_INTENSITY,
      COVARIANCE(AREA, STD_INTENSITY) AS COV_AREA_STD_INTENSITY,
      COVARIANCE(AREA, ENTROPY) AS COV_AREA_ENTROPY,
      COVARIANCE(AREA, ENERGY) AS COV_AREA_ENERGY,
      COVARIANCE(AREA, SKEWNESS) AS COV_AREA_SKEWNESS,
      COVARIANCE(AREA, KURTOSIS) AS COV_AREA_KURTOSIS,
      COVARIANCE(AREA, MEAN_GRADIENT_MAGNITUDE) AS COV_AREA_MEAN_GRADIENT_MAGNITUDE,
      COVARIANCE(AREA, STD_GRADIENT_MAGNITUDE) AS COV_AREA_STD_GRADIENT_MAGNITUDE,
      COVARIANCE(AREA, ENTROPY_GRADIENT_MAGNITUDE) AS COV_AREA_ENTROPY_GRADIENT_MAGNITUDE,              
      COVARIANCE(AREA, ENERGY_GRADIENT_MAGNITUDE) AS COV_AREA_ENERGY_GRADIENT_MAGNITUDE,
      COVARIANCE(AREA, SKEWNESS_GRADIENT_MAGNITUDE) AS COV_AREA_SKEWNESS_GRADIENT_MAGNITUDE,
      COVARIANCE(AREA, KURTOSIS_GRADIENT_MAGNITUDE) AS COV_AREA_KURTOSIS_GRADIENT_MAGNITUDE,
      COVARIANCE(AREA, SUM_CANNY_PIXEL) AS COV_AREA_SUM_CANNY_PIXEL,
      COVARIANCE(AREA, MEAN_CANNY_PIXEL) AS COV_AREA_MEAN_CANNY_PIXEL
FROM  pais.calculation_flat f, pais.collection c
WHERE f.pais_uid=c.pais_uid AND c.methodname ='NS-MORPH' AND c.sequencenumber ='1' and c.pais_uid ='TCGA-02-0001-01Z-00-DX2_20x_20x_NS-MORPH_1';

update bchmk.querytime set endtime = current timestamp where queryname = 'meanfeaturevectorcovsingleslide';
select endtime - starttime from bchmk.querytime where queryname =  'meanfeaturevectorcovsingleslide';
