CREATE  INDEX VALIDATION.TF_SUBREGIONTILENAME ON VALIDATION.SUBREGION_TEXTURE_FEATURE (SUBREGIONTILENAME ASC)  PCTFREE 10 MINPCTUSED 10 ALLOW REVERSE SCANS  PAGE SPLIT SYMMETRIC COLLECT  SAMPLED DETAILED  STATISTICS;

CREATE  INDEX VALIDATION.SUBREGION_TILENAME_IDX ON VALIDATION.SUBREGION (SUBREGIONTILENAME ASC)  PCTFREE 10 MINPCTUSED 10 ALLOW REVERSE SCANS  PAGE SPLIT SYMMETRIC COLLECT  SAMPLED DETAILED  STATISTICS ;
