CONNECT TO PAISEXT;
IMPORT FROM "/tmp/subregionmarkupexport.txt" OF DEL MODIFIED BY COLDEL, METHOD P (1, 2, 3, 4) MESSAGES "/tmp/subregionmarkupimport.txt" INSERT INTO VALIDATION.SUBREGION_MARKUP (PAIS_UID, TILENAME, SUBREGIONNAME, MARKUP_ID);
CONNECT RESET;
